EDITOR=nvim
VISUAL_EDITOR=$EDITOR
ALTERNATE_EDITOR=vim

export EDITOR VISUAL_EDITOR ALTERNATE_EDITOR

PAGER=bat
MANPAGER=less

export PAGER MANPAGER

export QT_QPA_PLATFORMTHEME=qt5ct

export QUTE_TRANS_TARGET=fr
